### ISSUE TITLE
Incompatibile con Linux 64-bit

### ISSUE THREAD

**Issue by free-variation** [CIRCSE/LEMLAT3#9]
Il programma `lemlat`, almeno nella versione contenuta nell' archivio `linux_embedded.tgz`, non e' eseguibile su sistemi Linux 64-bit.  Risulta necessaria la installazione del 32-bit subsystem.

Per esempio, in ambito Ubuntu, bisogna prima eseguire:

```bash
sudo apt-get install libc6-i386 
sudo apt-get install ia32-libs
```

**Comment by gersh0m** [comment]
Careful!!
That  information it is misleading.
Linux binaries are, at the moment, 32bit executable.
In order to run it on a 64-bit linux distro, additional libraries must be installed depending on the distro itself.
The above packages may work on some  (Ubuntu) distro  and not on other... 

The following is a list of needed libreries/packages on recent (e.g. 16.04) Ubuntu versions:

libc6-1686
lib32z1
gcc-multilib
libwrap0:1386
libaio:i386

Anyway 64 bits native binaries will be available in the days...

**Comment by free-variation** [comment]
Thank you for the quick reply @gersh0m.  Are you saying the above is "misleading" because the meta-package `ia32-libs` has, at times, been under threat of deprecation?  In any case having the more precise list of 32bit lib dependencies is better, agreed.  And we look forward to the 64-bit binary.

**Comment by gersh0m** [comment]
Linux 64 native binaries are availables
